services:
  mongo:
    #image: mongo:7
    build:
      context: ./mongodb
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USERNAME_MDB:?error}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD_MDB:?error}
      #MONGO_INITDB_DATABASE: hcare_db
    command: mongod --auth
    volumes:
      - type: bind
        source: ./databases
        target: /data/db
    networks:
      - app-network
  # Script python
  app:
    build: .
    container_name: migration_db
    depends_on:
      - mongo
    environment:
      - MONGO_URI_H=mongodb://${USERNAME_MDB:?error}:${PASSWORD_MDB:?error}@mongo:27017/
      - MONGO_URI_P=mongodb://${USERNAME_MDB:?error}:${PASSWORD_MDB:?error}@mongo:27017/
      - DB_NAME_H=${NAME_MDBH:?error}
      - DB_NAME_P=${NAME_MDBP:?error}
    volumes:
      - ./data:/appmdb/data
    networks:
      - app-network
networks:
  app-network:

 
